-- CREATE TABLE USERS
-- (
--   ID             SERIAL PRIMARY KEY,
--   FirstName      VARCHAR(50),
--   LastName       VARCHAR(50),
--   Email          VARCHAR(100) NOT NULL UNIQUE,
--   Nickname       VARCHAR(50) NOT NULL UNIQUE,
--   Password       VARCHAR(50),
--   PhotoURL       VARCHAR(50),
--   AccessRights   SMALLINT,
--   UserLevel      INTEGER REFERENCES LEVELS (ID),
--   DateStamp      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );